#!/bin/sh
set -e
port=5434
if [ -f /usr/share/postgresql/default/users ] || [ -f /usr/share/postgresql/default/extensions ]; then
  # In reality we should accept more than just these two files but for now this works.

  touch /var/log/postgres.tmp.log
  chpst -u postgres postgres -D /srv/postgresql -c "config_file=/etc/postgresql/postgresql.conf" \
    -c "port=$port" 1> /var/log/postgres.tmp.log 2>&1 &
  pid=$!

  count=0; started=
  while [ "$count" -lt 12 ]; do
    count=$(echo "$(($count+1))")
    chpst -u postgres:postgres psql --port=$port -d postgres -c '\l' \
        1> /dev/null 2>&1 && {
      started=true
      break
    }

    sleep 1
  done

  if [ -z "$started" ]; then
    echo "Unable to start Postgresql, maybe this log will help: "
    cat /var/log/postgres.tmp.log
    rm -rf /var/log/postgres.tmp.log
    exit 1
  fi

  if [ -f /usr/share/postgresql/default/users ] && rm -rf /var/log/postgres.tmp.log; then
    for v in $(cat /usr/share/postgresql/default/users); do
      user=$(echo $v | awk -F: '{ print $1 }')
      pass=$(echo $v | awk -F: '{ print $2 }')
      data=$(echo $v | awk -F: '{ print $3 }')

      if [ "$pass" ]; then
        if ! chpst -u postgres:postgres psql --port=$port -tAc \
            "SELECT 1 FROM pg_roles WHERE rolname='$user'" | grep -q 1;
          then chpst -u postgres:postgres createuser --port=$port \
            --no-superuser --no-createdb --echo $user
        fi

        chpst -u postgres:postgres psql --port=$port -c \
          "ALTER USER $user WITH PASSWORD '$pass';" >/dev/null
      fi

      chpst -u postgres:postgres createdb \
        --port=$port --owner=$user \
          --echo $data || echo "Database already existed, moving along."
    done
  fi

  if [ -f /usr/share/postgresql/default/extensions ]; then
    for v in $(cat /usr/share/postgresql/default/extensions); do
      data=$(echo $v | awk -F: '{ print $1 }')
      exts=$(echo $v | awk -F: '{ print $2 }')
      printf "CREATE EXTENSION %s ON %s\n" "$exts" "$data"
      chpst -u postgres:postgres psql --port=$port -d $data -c \
        "CREATE EXTENSION \"$exts\"" 1> /dev/null
    done
  fi

  rm -rf \
    /var/log/postgres.tmp.log
  kill $pid
  wait $pid
fi
exit 0
