#!/bin/sh
set -e

cd /opt/discourse
for c in tmp:create db:migrate assets:precompile assets:clean uploads:clean_up avatars:clean; do
  count=0; while [ "$count" -lt 4 ]; do
    set +e
    count=$(echo "$(($count+1))")
    if [ $count -gt 1 ]; then
      printf "\nRetrying\n"
    fi

    chpst -u discourse:discourse rake \
      "$c" && break
    set -e
    sleep \
      6
  done

  if [ "$count" -gt 3 ]; then
    exit 1
  fi
done
