# Scope is quick self contained transportable devel env - severe security issue presents!

FROM fedora:20
MAINTAINER av@levm.eu
#Install prereq
RUN yum install -y timeline


#start nginx
CMD ["timeline"]

